export const config = {
    PRODUCTS_BASE_URL: import.meta.env.VITE_API_PRODUCTS_SERVICE_URL,
    ORDERS_BASE_URL: import.meta.env.VITE_API_PRODUCTS_ORDERS_URL,
    ADMIN_BASE_URL: import.meta.env.VITE_API_ADMIN_SERVICE_URL,
    AUTH_BASE_URL: import.meta.env.VITE_API_AUTH_SERVICE_URL,
    PRODUCTS_IMAGES_BASE_URL: import.meta.env.VITE_API_PRODUCTS_IMGAES_SERVICE_URL,
}
